dynamic values

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,11 +30,23 @@ jobs:
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
           SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
         run: serverless deploy --verbose
-# Step to Deploy API Gateway to a Stage
+
+      # Step to Get API ID and Deploy API Gateway to a Stage
       - name: Deploy API Gateway to Stage
         env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
           DEPLOYMENT_STAGE: ${{ secrets.DEPLOYMENT_STAGE }}
-          API_ID: ${{ secrets.API_ID }}
+          API_NAME: ${{ secrets.API_NAME }}
         run: |
-          echo "Deploying API Gateway"
+          echo "Fetching API ID for API: $API_NAME"
+          API_ID=$(aws apigateway get-rest-apis --query "items[?name=='$API_NAME'].id" --output text)
+          
+          if [ -z "$API_ID" ]; then
+            echo "Error: API ID for '$API_NAME' not found."
+            exit 1
+          fi
+
+          echo "Deploying API Gateway with ID: $API_ID to stage: $DEPLOYMENT_STAGE"
           aws apigateway create-deployment --rest-api-id $API_ID --stage-name $DEPLOYMENT_STAGE
